# Site settings
title: contacts.gg
email: contact@jasemagee.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://contacts.gg" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
